// Code generated by the Lingua Franca compiler from:
// file://Users/sailor/Developer/git/EDAN15/Lab1/lab1_5.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/sailor/Developer/git/EDAN15/src-gen/Lab1/lab1_5"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_source.h"
#include "_sink.h"
#include "_stringln.h"
#include "__lf_gendelay_c09f7d0a.h"
#include "_lab1_5_main.h"
typedef enum {
    lab1_5_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[lab1_5_main],"lab1_5",lab1_5_main,_lf_number_of_workers,0,1,1,0,6,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _lab1_5_main_main_self_t* lab1_5_main_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_5_main_self);
    _source_self_t* lab1_5_source_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_5_source_self);
    _sink_self_t* lab1_5_sink_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_5_sink_self);
    _stringln_self_t* lab1_5_stringln_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_5_stringln_self);
    __lf_gendelay_c09f7d0a_self_t* lab1_5_delay_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_5_delay_self);
    // ***** Start initializing lab1_5 of class lab1_5
    lab1_5_main_self[0] = new__lab1_5_main();
    lab1_5_main_self[0]->base.environment = &envs[lab1_5_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
    {
        _lab1_5_main_main_self_t *self = lab1_5_main_self[0];
        // ***** Start initializing lab1_5.Source of class Source
        lab1_5_source_self[0] = new__source();
        lab1_5_source_self[0]->base.environment = &envs[lab1_5_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        lab1_5_source_self[0]->start = MSEC(100);
        lab1_5_source_self[0]->incr = MSEC(100);
        // width of -2 indicates that it is not a multiport.
        lab1_5_source_self[0]->_lf_out_width = -2;
        envs[lab1_5_main].startup_reactions[startup_reaction_count[lab1_5_main]++] = &lab1_5_source_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        lab1_5_source_self[0]->interval = lab1_5_source_self[0]->start;
        // Initializing action lab1_5.Source.a
        lab1_5_source_self[0]->_lf__a.offset = 0;
        lab1_5_source_self[0]->_lf__a.period = -1;
        lab1_5_source_self[0]->_lf__a.last_tag = NEVER_TAG;
        lab1_5_source_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(lab1_5_source_self[0]->_lf__a),
        0);
        lab1_5_source_self[0]->_lf__a.status = absent;
        lab1_5_source_self[0]->_lf__reaction_0.deadline = NEVER;
        lab1_5_source_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing lab1_5.Source
    }
    {
        _lab1_5_main_main_self_t *self = lab1_5_main_self[0];
        // ***** Start initializing lab1_5.Sink of class Sink
        lab1_5_sink_self[0] = new__sink();
        lab1_5_sink_self[0]->base.environment = &envs[lab1_5_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab1_5_sink_self[0]->_lf_in_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        lab1_5_sink_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing lab1_5.Sink
    }
    {
        _lab1_5_main_main_self_t *self = lab1_5_main_self[0];
        // ***** Start initializing lab1_5.Stringln of class Stringln
        lab1_5_stringln_self[0] = new__stringln();
        lab1_5_stringln_self[0]->base.environment = &envs[lab1_5_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab1_5_stringln_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab1_5_stringln_self[0]->_lf_out_int_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab1_5_stringln_self[0]->_lf_in_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab1_5_stringln_self[0]->_lf_in_int_width = -2;
        envs[lab1_5_main].shutdown_reactions[shutdown_reaction_count[lab1_5_main]++] = &lab1_5_stringln_self[0]->_lf__reaction_2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static int _initial = 0;
            lab1_5_stringln_self[0]->total = _initial;
        } // End scoping.
    
        lab1_5_stringln_self[0]->_lf__reaction_0.deadline = NEVER;
        lab1_5_stringln_self[0]->_lf__reaction_1.deadline = NEVER;
        lab1_5_stringln_self[0]->_lf__reaction_2.deadline = NEVER;
        //***** End initializing lab1_5.Stringln
    }
    {
        _lab1_5_main_main_self_t *self = lab1_5_main_self[0];
        // ***** Start initializing lab1_5.delay of class _lf_GenDelay_c09f7d0a
        lab1_5_delay_self[0] = new___lf_gendelay_c09f7d0a();
        lab1_5_delay_self[0]->base.environment = &envs[lab1_5_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        lab1_5_delay_self[0]->delay = 0;
        // width of -2 indicates that it is not a multiport.
        lab1_5_delay_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab1_5_delay_self[0]->_lf_inp_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initializing action lab1_5.delay.act
        lab1_5_delay_self[0]->_lf__act.offset = 0;
        lab1_5_delay_self[0]->_lf__act.period = -1;
        lab1_5_delay_self[0]->_lf__act.last_tag = NEVER_TAG;
        lab1_5_delay_self[0]->_lf__act.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(lab1_5_delay_self[0]->_lf__act),
        sizeof(int));
        lab1_5_delay_self[0]->_lf__act.status = absent;
        lab1_5_delay_self[0]->_lf__reaction_0.deadline = NEVER;
        lab1_5_delay_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing lab1_5.delay
    }
    //***** End initializing lab1_5
    // **** Start deferred initialize for lab1_5
    {
    
    
    
        // **** Start deferred initialize for lab1_5.Source
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_5.Source.
            lab1_5_source_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of lab1_5.Source
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of lab1_5.Source.
            lab1_5_source_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab1_5_source_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab1_5_source_self[0]->base.allocations);
            lab1_5_source_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab1_5_source_self[0]->base.allocations);
            lab1_5_source_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab1_5_source_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab1_5_source_self[0]->_lf__reaction_1.output_produced[count++] = &lab1_5_source_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of lab1_5.Source
        
        }
        // **** End of deferred initialize for lab1_5.Source
        // **** Start deferred initialize for lab1_5.Sink
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_5.Sink.
            lab1_5_sink_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of lab1_5.Sink
        
        }
        // **** End of deferred initialize for lab1_5.Sink
        // **** Start deferred initialize for lab1_5.Stringln
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_5.Stringln.
            lab1_5_stringln_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab1_5_stringln_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab1_5_stringln_self[0]->base.allocations);
            lab1_5_stringln_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab1_5_stringln_self[0]->base.allocations);
            lab1_5_stringln_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab1_5_stringln_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab1_5_stringln_self[0]->_lf__reaction_0.output_produced[count++] = &lab1_5_stringln_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of lab1_5.Stringln
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of lab1_5.Stringln.
            lab1_5_stringln_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab1_5_stringln_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab1_5_stringln_self[0]->base.allocations);
            lab1_5_stringln_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab1_5_stringln_self[0]->base.allocations);
            lab1_5_stringln_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab1_5_stringln_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab1_5_stringln_self[0]->_lf__reaction_1.output_produced[count++] = &lab1_5_stringln_self[0]->_lf_out_int.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of lab1_5.Stringln
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of lab1_5.Stringln.
            lab1_5_stringln_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 2 of lab1_5.Stringln
        
        }
        // **** End of deferred initialize for lab1_5.Stringln
        // **** Start deferred initialize for lab1_5.delay
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_5.delay.
            lab1_5_delay_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab1_5_delay_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab1_5_delay_self[0]->base.allocations);
            lab1_5_delay_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab1_5_delay_self[0]->base.allocations);
            lab1_5_delay_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab1_5_delay_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab1_5_delay_self[0]->_lf__reaction_0.output_produced[count++] = &lab1_5_delay_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of lab1_5.delay
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of lab1_5.delay.
            lab1_5_delay_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of lab1_5.delay
        
        }
        // **** End of deferred initialize for lab1_5.delay
    }
    // **** End of deferred initialize for lab1_5
    // **** Start non-nested deferred initialize for lab1_5
    {
    
    
    
        // **** Start non-nested deferred initialize for lab1_5.Source
        {
        
            // For reference counting, set num_destinations for port lab1_5.Source.out.
            // Iterate over range lab1_5.Source.out(0,1)->[lab1_5.Stringln.in(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab1_5_source_self[src_runtime]->_lf_out._base.num_destinations = 1;
                lab1_5_source_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)lab1_5_source_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range lab1_5.Source.out(0,1)->[lab1_5.Stringln.in(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of lab1_5.Source triggers 1 downstream reactions
                    // through port lab1_5.Source.out.
                    lab1_5_source_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of lab1_5.Source, allocate an
                    // array of trigger pointers for downstream reactions through port lab1_5.Source.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &lab1_5_source_self[src_runtime]->base.allocations); 
                    lab1_5_source_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges lab1_5.Source.out(0,1)->[lab1_5.Stringln.in(0,1)] and lab1_5.Stringln.in(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range lab1_5.Stringln.in(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port lab1_5.Stringln.in's trigger struct.
                        lab1_5_source_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &lab1_5_stringln_self[dst_runtime]->_lf__in;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for lab1_5.Source
        // **** Start non-nested deferred initialize for lab1_5.Sink
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for lab1_5.Sink
        // **** Start non-nested deferred initialize for lab1_5.Stringln
        {
        
            // For reference counting, set num_destinations for port lab1_5.Stringln.out.
            // Iterate over range lab1_5.Stringln.out(0,1)->[lab1_5.Sink.in(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab1_5_stringln_self[src_runtime]->_lf_out._base.num_destinations = 1;
                lab1_5_stringln_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)lab1_5_stringln_self[src_runtime];
            }
            // For reference counting, set num_destinations for port lab1_5.Stringln.out_int.
            // Iterate over range lab1_5.Stringln.out_int(0,1)->[lab1_5.delay.inp(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab1_5_stringln_self[src_runtime]->_lf_out_int._base.num_destinations = 1;
                lab1_5_stringln_self[src_runtime]->_lf_out_int._base.source_reactor = (self_base_t*)lab1_5_stringln_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range lab1_5.Stringln.out(0,1)->[lab1_5.Sink.in(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of lab1_5.Stringln triggers 1 downstream reactions
                    // through port lab1_5.Stringln.out.
                    lab1_5_stringln_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of lab1_5.Stringln, allocate an
                    // array of trigger pointers for downstream reactions through port lab1_5.Stringln.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &lab1_5_stringln_self[src_runtime]->base.allocations); 
                    lab1_5_stringln_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges lab1_5.Stringln.out(0,1)->[lab1_5.Sink.in(0,1)] and lab1_5.Sink.in(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range lab1_5.Sink.in(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port lab1_5.Sink.in's trigger struct.
                        lab1_5_stringln_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &lab1_5_sink_self[dst_runtime]->_lf__in;
                    }
                }
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range lab1_5.Stringln.out_int(0,1)->[lab1_5.delay.inp(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of lab1_5.Stringln triggers 1 downstream reactions
                    // through port lab1_5.Stringln.out_int.
                    lab1_5_stringln_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of lab1_5.Stringln, allocate an
                    // array of trigger pointers for downstream reactions through port lab1_5.Stringln.out_int
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &lab1_5_stringln_self[src_runtime]->base.allocations); 
                    lab1_5_stringln_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges lab1_5.Stringln.out_int(0,1)->[lab1_5.delay.inp(0,1)] and lab1_5.delay.inp(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range lab1_5.delay.inp(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port lab1_5.delay.inp's trigger struct.
                        lab1_5_stringln_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &lab1_5_delay_self[dst_runtime]->_lf__inp;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for lab1_5.Stringln
        // **** Start non-nested deferred initialize for lab1_5.delay
        {
        
            // For reference counting, set num_destinations for port lab1_5.delay.out.
            // Iterate over range lab1_5.delay.out(0,1)->[lab1_5.Stringln.in_int(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab1_5_delay_self[src_runtime]->_lf_out._base.num_destinations = 1;
                lab1_5_delay_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)lab1_5_delay_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range lab1_5.delay.out(0,1)->[lab1_5.Stringln.in_int(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of lab1_5.delay triggers 1 downstream reactions
                    // through port lab1_5.delay.out.
                    lab1_5_delay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of lab1_5.delay, allocate an
                    // array of trigger pointers for downstream reactions through port lab1_5.delay.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &lab1_5_delay_self[src_runtime]->base.allocations); 
                    lab1_5_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges lab1_5.delay.out(0,1)->[lab1_5.Stringln.in_int(0,1)] and lab1_5.Stringln.in_int(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range lab1_5.Stringln.in_int(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port lab1_5.Stringln.in_int's trigger struct.
                        lab1_5_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &lab1_5_stringln_self[dst_runtime]->_lf__in_int;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for lab1_5.delay
    }
    // **** End of non-nested deferred initialize for lab1_5
    // Connect inputs and outputs for reactor lab1_5.
    // Connect inputs and outputs for reactor lab1_5.Source.
    // Connect lab1_5.Source.out(0,1)->[lab1_5.Stringln.in(0,1)] to port lab1_5.Stringln.in(0,1)
    // Iterate over ranges lab1_5.Source.out(0,1)->[lab1_5.Stringln.in(0,1)] and lab1_5.Stringln.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range lab1_5.Stringln.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            lab1_5_stringln_self[dst_runtime]->_lf_in = (_stringln_in_t*)&lab1_5_source_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor lab1_5.Sink.
    // Connect inputs and outputs for reactor lab1_5.Stringln.
    // Connect lab1_5.Stringln.out(0,1)->[lab1_5.Sink.in(0,1)] to port lab1_5.Sink.in(0,1)
    // Iterate over ranges lab1_5.Stringln.out(0,1)->[lab1_5.Sink.in(0,1)] and lab1_5.Sink.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range lab1_5.Sink.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            lab1_5_sink_self[dst_runtime]->_lf_in = (_sink_in_t*)&lab1_5_stringln_self[src_runtime]->_lf_out;
        }
    }
    // Connect lab1_5.Stringln.out_int(0,1)->[lab1_5.delay.inp(0,1)] to port lab1_5.delay.inp(0,1)
    // Iterate over ranges lab1_5.Stringln.out_int(0,1)->[lab1_5.delay.inp(0,1)] and lab1_5.delay.inp(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range lab1_5.delay.inp(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            lab1_5_delay_self[dst_runtime]->_lf_inp = (__lf_gendelay_c09f7d0a_inp_t*)&lab1_5_stringln_self[src_runtime]->_lf_out_int;
        }
    }
    // Connect inputs and outputs for reactor lab1_5.delay.
    // Connect lab1_5.delay.out(0,1)->[lab1_5.Stringln.in_int(0,1)] to port lab1_5.Stringln.in_int(0,1)
    // Iterate over ranges lab1_5.delay.out(0,1)->[lab1_5.Stringln.in_int(0,1)] and lab1_5.Stringln.in_int(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range lab1_5.Stringln.in_int(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            lab1_5_stringln_self[dst_runtime]->_lf_in_int = (_stringln_in_int_t*)&lab1_5_delay_self[src_runtime]->_lf_out;
        }
    }
    {
        {
            // Add action lab1_5.Source.a to array of is_present fields.
            envs[lab1_5_main].is_present_fields[0] 
                    = &lab1_5_source_self[0]->_lf_a.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action lab1_5.Source.a to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[0] 
                    = &lab1_5_source_self[0]->_lf_a.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
    }
    {
        {
            // Add action lab1_5.delay.act to array of is_present fields.
            envs[lab1_5_main].is_present_fields[1] 
                    = &lab1_5_delay_self[0]->_lf_act.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action lab1_5.delay.act to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[1] 
                    = &lab1_5_delay_self[0]->_lf_act.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port lab1_5.Source.out to array of is_present fields.
            envs[lab1_5_main].is_present_fields[2 + count] = &lab1_5_source_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab1_5.Source.out to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[2 + count] = &lab1_5_source_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port lab1_5.Stringln.out to array of is_present fields.
            envs[lab1_5_main].is_present_fields[3 + count] = &lab1_5_stringln_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab1_5.Stringln.out to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[3 + count] = &lab1_5_stringln_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port lab1_5.Stringln.out_int to array of is_present fields.
            envs[lab1_5_main].is_present_fields[3 + count] = &lab1_5_stringln_self[0]->_lf_out_int.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab1_5.Stringln.out_int to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[3 + count] = &lab1_5_stringln_self[0]->_lf_out_int.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port lab1_5.delay.out to array of is_present fields.
            envs[lab1_5_main].is_present_fields[5 + count] = &lab1_5_delay_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab1_5.delay.out to array of intended_tag fields.
            envs[lab1_5_main]._lf_intended_tag_fields[5 + count] = &lab1_5_delay_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance lab1_5
    {
    
        // Set reaction priorities for ReactorInstance lab1_5.Source
        {
            lab1_5_source_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_source_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            lab1_5_source_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_source_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance lab1_5.Sink
        {
            lab1_5_sink_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_sink_self[0]->_lf__reaction_0.index = 0xffffffffffff0003LL;
        }
    
    
        // Set reaction priorities for ReactorInstance lab1_5.Stringln
        {
            lab1_5_stringln_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_stringln_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
            lab1_5_stringln_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_stringln_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
            lab1_5_stringln_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_stringln_self[0]->_lf__reaction_2.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance lab1_5.delay
        {
            lab1_5_delay_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_delay_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            lab1_5_delay_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_5_delay_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[5] = 
        {2, 1, 1, 2, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 5};
    lf_sched_init(
        &envs[lab1_5_main],
        envs[lab1_5_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        lf_latest_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
