// Code generated by the Lingua Franca compiler from:
// file://Users/sailor/Developer/git/EDAN15/Lab2/lab_2.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/sailor/Developer/git/EDAN15/src-gen/Lab2/lab_2"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true", "-o", "100", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 6;
        default_argv = _lf_default_argv;
}
#include "_input.h"
#include "_output.h"
#include "_machine.h"
#include "_lab_2_main.h"
typedef enum {
    lab_2_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[lab_2_main],"lab_2",lab_2_main,_lf_number_of_workers,0,1,0,0,4,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _lab_2_main_main_self_t* lab_2_main_self[1];
    SUPPRESS_UNUSED_WARNING(lab_2_main_self);
    _input_self_t* lab_2_input_self[1];
    SUPPRESS_UNUSED_WARNING(lab_2_input_self);
    _output_self_t* lab_2_output_self[1];
    SUPPRESS_UNUSED_WARNING(lab_2_output_self);
    _machine_self_t* lab_2_machine_self[1];
    SUPPRESS_UNUSED_WARNING(lab_2_machine_self);
    // ***** Start initializing lab_2 of class lab_2
    lab_2_main_self[0] = new__lab_2_main();
    lab_2_main_self[0]->base.environment = &envs[lab_2_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
    {
        _lab_2_main_main_self_t *self = lab_2_main_self[0];
        // ***** Start initializing lab_2.Input of class Input
        lab_2_input_self[0] = new__input();
        lab_2_input_self[0]->base.environment = &envs[lab_2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab_2_input_self[0]->_lf_cancel_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_input_self[0]->_lf_sel_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_input_self[0]->_lf_coin_width = -2;
        envs[lab_2_main].startup_reactions[startup_reaction_count[lab_2_main]++] = &lab_2_input_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static lf_thread_t _initial = 0;
            lab_2_input_self[0]->thread_id = _initial;
        } // End scoping.
        // Initializing action lab_2.Input.a
        lab_2_input_self[0]->_lf__a.offset = 0;
        lab_2_input_self[0]->_lf__a.period = -1;
        lab_2_input_self[0]->_lf__a.last_tag = NEVER_TAG;
        lab_2_input_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(lab_2_input_self[0]->_lf__a),
        sizeof(int));
        lab_2_input_self[0]->_lf__a.status = absent;
        lab_2_input_self[0]->_lf__reaction_0.deadline = NEVER;
        lab_2_input_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing lab_2.Input
    }
    {
        _lab_2_main_main_self_t *self = lab_2_main_self[0];
        // ***** Start initializing lab_2.Output of class Output
        lab_2_output_self[0] = new__output();
        lab_2_output_self[0]->base.environment = &envs[lab_2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab_2_output_self[0]->_lf_change_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_output_self[0]->_lf_beverage_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        lab_2_output_self[0]->_lf__reaction_0.deadline = NEVER;
        lab_2_output_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing lab_2.Output
    }
    {
        _lab_2_main_main_self_t *self = lab_2_main_self[0];
        // ***** Start initializing lab_2.Machine of class Machine
        lab_2_machine_self[0] = new__machine();
        lab_2_machine_self[0]->base.environment = &envs[lab_2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        static int lab_2_machine_stock[] = {2,2,2};
        lab_2_machine_self[0]->stock = lab_2_machine_stock;
        // width of -2 indicates that it is not a multiport.
        lab_2_machine_self[0]->_lf_change_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_machine_self[0]->_lf_beverage_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_machine_self[0]->_lf_cancel_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_machine_self[0]->_lf_sel_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab_2_machine_self[0]->_lf_coin_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        //***** End initializing lab_2.Machine
    }
    //***** End initializing lab_2
    // **** Start deferred initialize for lab_2
    {
    
    
    
        // **** Start deferred initialize for lab_2.Input
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab_2.Input.
            lab_2_input_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of lab_2.Input
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of lab_2.Input.
            lab_2_input_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab_2_input_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &lab_2_input_self[0]->base.allocations);
            lab_2_input_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &lab_2_input_self[0]->base.allocations);
            lab_2_input_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &lab_2_input_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab_2_input_self[0]->_lf__reaction_1.output_produced[count++] = &lab_2_input_self[0]->_lf_cancel.is_present;
                }
                {
                    lab_2_input_self[0]->_lf__reaction_1.output_produced[count++] = &lab_2_input_self[0]->_lf_sel.is_present;
                }
                {
                    lab_2_input_self[0]->_lf__reaction_1.output_produced[count++] = &lab_2_input_self[0]->_lf_coin.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of lab_2.Input
        
        }
        // **** End of deferred initialize for lab_2.Input
        // **** Start deferred initialize for lab_2.Output
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab_2.Output.
            lab_2_output_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of lab_2.Output
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of lab_2.Output.
            lab_2_output_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of lab_2.Output
        
        }
        // **** End of deferred initialize for lab_2.Output
        // **** Start deferred initialize for lab_2.Machine
        {
        
        
        
        }
        // **** End of deferred initialize for lab_2.Machine
    }
    // **** End of deferred initialize for lab_2
    // **** Start non-nested deferred initialize for lab_2
    {
    
    
    
        // **** Start non-nested deferred initialize for lab_2.Input
        {
        
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { lab_2_input_self[0]->_lf_cancel._base.source_reactor = (self_base_t*)lab_2_input_self[0]; }
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { lab_2_input_self[0]->_lf_sel._base.source_reactor = (self_base_t*)lab_2_input_self[0]; }
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { lab_2_input_self[0]->_lf_coin._base.source_reactor = (self_base_t*)lab_2_input_self[0]; }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            }
        
        }
        // **** End of non-nested deferred initialize for lab_2.Input
        // **** Start non-nested deferred initialize for lab_2.Output
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for lab_2.Output
        // **** Start non-nested deferred initialize for lab_2.Machine
        {
        
            // For reference counting, set num_destinations for port lab_2.Machine.change.
            // Iterate over range lab_2.Machine.change(0,1)->[lab_2.Output.change(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab_2_machine_self[src_runtime]->_lf_change._base.num_destinations = 1;
                lab_2_machine_self[src_runtime]->_lf_change._base.source_reactor = (self_base_t*)lab_2_machine_self[src_runtime];
            }
            // For reference counting, set num_destinations for port lab_2.Machine.beverage.
            // Iterate over range lab_2.Machine.beverage(0,1)->[lab_2.Output.beverage(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab_2_machine_self[src_runtime]->_lf_beverage._base.num_destinations = 1;
                lab_2_machine_self[src_runtime]->_lf_beverage._base.source_reactor = (self_base_t*)lab_2_machine_self[src_runtime];
            }
        
        
        }
        // **** End of non-nested deferred initialize for lab_2.Machine
    }
    // **** End of non-nested deferred initialize for lab_2
    // Connect inputs and outputs for reactor lab_2.
    // Connect inputs and outputs for reactor lab_2.Input.
    
    
    
    // Connect inputs and outputs for reactor lab_2.Output.
    // Connect inputs and outputs for reactor lab_2.Machine.
    {
        {
            // Add action lab_2.Input.a to array of is_present fields.
            envs[lab_2_main].is_present_fields[0] 
                    = &lab_2_input_self[0]->_lf_a.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action lab_2.Input.a to array of intended_tag fields.
            envs[lab_2_main]._lf_intended_tag_fields[0] 
                    = &lab_2_input_self[0]->_lf_a.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port lab_2.Input.cancel to array of is_present fields.
            envs[lab_2_main].is_present_fields[1 + count] = &lab_2_input_self[0]->_lf_cancel.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab_2.Input.cancel to array of intended_tag fields.
            envs[lab_2_main]._lf_intended_tag_fields[1 + count] = &lab_2_input_self[0]->_lf_cancel.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port lab_2.Input.sel to array of is_present fields.
            envs[lab_2_main].is_present_fields[1 + count] = &lab_2_input_self[0]->_lf_sel.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab_2.Input.sel to array of intended_tag fields.
            envs[lab_2_main]._lf_intended_tag_fields[1 + count] = &lab_2_input_self[0]->_lf_sel.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port lab_2.Input.coin to array of is_present fields.
            envs[lab_2_main].is_present_fields[1 + count] = &lab_2_input_self[0]->_lf_coin.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab_2.Input.coin to array of intended_tag fields.
            envs[lab_2_main]._lf_intended_tag_fields[1 + count] = &lab_2_input_self[0]->_lf_coin.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    
    // Set reaction priorities for ReactorInstance lab_2
    {
    
        // Set reaction priorities for ReactorInstance lab_2.Input
        {
            lab_2_input_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab_2_input_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            lab_2_input_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab_2_input_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance lab_2.Output
        {
            lab_2_output_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab_2_output_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            lab_2_output_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab_2_output_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[2] = 
        {2, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 2};
    lf_sched_init(
        &envs[lab_2_main],
        envs[lab_2_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        lf_latest_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
