// Code generated by the Lingua Franca compiler from:
// file://Users/sailor/Developer/git/EDAN15/Lab2/Vending_Machine_state_check_first.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/sailor/Developer/git/EDAN15/src-gen/Lab2/Vending_Machine_state_check_first"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "_input.h"
#include "_output.h"
#include "_machine.h"
#include "_vending_machine_state_check_first_main.h"
typedef enum {
    vending_machine_state_check_first_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[vending_machine_state_check_first_main],"Vending_Machine_state_check_first",vending_machine_state_check_first_main,_lf_number_of_workers,0,1,0,0,6,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _vending_machine_state_check_first_main_main_self_t* vending_machine_state_check_first_main_self[1];
    SUPPRESS_UNUSED_WARNING(vending_machine_state_check_first_main_self);
    _input_self_t* vending_machine_state_check_first_input_self[1];
    SUPPRESS_UNUSED_WARNING(vending_machine_state_check_first_input_self);
    _output_self_t* vending_machine_state_check_first_output_self[1];
    SUPPRESS_UNUSED_WARNING(vending_machine_state_check_first_output_self);
    _machine_self_t* _nding_machine_state_check_first_machine_self[1];
    SUPPRESS_UNUSED_WARNING(_nding_machine_state_check_first_machine_self);
    // ***** Start initializing Vending_Machine_state_check_first of class Vending_Machine_state_check_first
    vending_machine_state_check_first_main_self[0] = new__vending_machine_state_check_first_main();
    vending_machine_state_check_first_main_self[0]->base.environment = &envs[vending_machine_state_check_first_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
    {
        _vending_machine_state_check_first_main_main_self_t *self = vending_machine_state_check_first_main_self[0];
        // ***** Start initializing Vending_Machine_state_check_first.Input of class Input
        vending_machine_state_check_first_input_self[0] = new__input();
        vending_machine_state_check_first_input_self[0]->base.environment = &envs[vending_machine_state_check_first_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        vending_machine_state_check_first_input_self[0]->_lf_cancel_width = -2;
        // width of -2 indicates that it is not a multiport.
        vending_machine_state_check_first_input_self[0]->_lf_sel_width = -2;
        // width of -2 indicates that it is not a multiport.
        vending_machine_state_check_first_input_self[0]->_lf_coin_width = -2;
        envs[vending_machine_state_check_first_main].startup_reactions[startup_reaction_count[vending_machine_state_check_first_main]++] = &vending_machine_state_check_first_input_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static lf_thread_t _initial = 0;
            vending_machine_state_check_first_input_self[0]->thread_id = _initial;
        } // End scoping.
        // Initializing action Vending_Machine_state_check_first.Input.a
        vending_machine_state_check_first_input_self[0]->_lf__a.offset = 0;
        vending_machine_state_check_first_input_self[0]->_lf__a.period = -1;
        vending_machine_state_check_first_input_self[0]->_lf__a.last_tag = NEVER_TAG;
        vending_machine_state_check_first_input_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(vending_machine_state_check_first_input_self[0]->_lf__a),
        sizeof(int));
        vending_machine_state_check_first_input_self[0]->_lf__a.status = absent;
        vending_machine_state_check_first_input_self[0]->_lf__reaction_0.deadline = NEVER;
        vending_machine_state_check_first_input_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Vending_Machine_state_check_first.Input
    }
    {
        _vending_machine_state_check_first_main_main_self_t *self = vending_machine_state_check_first_main_self[0];
        // ***** Start initializing Vending_Machine_state_check_first.Output of class Output
        vending_machine_state_check_first_output_self[0] = new__output();
        vending_machine_state_check_first_output_self[0]->base.environment = &envs[vending_machine_state_check_first_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        vending_machine_state_check_first_output_self[0]->_lf_change_width = -2;
        // width of -2 indicates that it is not a multiport.
        vending_machine_state_check_first_output_self[0]->_lf_beverage_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        vending_machine_state_check_first_output_self[0]->_lf__reaction_0.deadline = NEVER;
        vending_machine_state_check_first_output_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Vending_Machine_state_check_first.Output
    }
    {
        _vending_machine_state_check_first_main_main_self_t *self = vending_machine_state_check_first_main_self[0];
        // ***** Start initializing Vending_Machine_state_check_first.Machine of class Machine
        _nding_machine_state_check_first_machine_self[0] = new__machine();
        _nding_machine_state_check_first_machine_self[0]->base.environment = &envs[vending_machine_state_check_first_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        static int _machine_state_check_first_machine_stock[] = {2,2,2};
        _nding_machine_state_check_first_machine_self[0]->stock = _machine_state_check_first_machine_stock;
        // width of -2 indicates that it is not a multiport.
        _nding_machine_state_check_first_machine_self[0]->_lf_change_width = -2;
        // width of -2 indicates that it is not a multiport.
        _nding_machine_state_check_first_machine_self[0]->_lf_beverage_width = -2;
        // width of -2 indicates that it is not a multiport.
        _nding_machine_state_check_first_machine_self[0]->_lf_cancel_width = -2;
        // width of -2 indicates that it is not a multiport.
        _nding_machine_state_check_first_machine_self[0]->_lf_sel_width = -2;
        // width of -2 indicates that it is not a multiport.
        _nding_machine_state_check_first_machine_self[0]->_lf_coin_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static int _initial = 0;
            _nding_machine_state_check_first_machine_self[0]->Machine_mode = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 0;
            _nding_machine_state_check_first_machine_self[0]->bev = _initial;
        } // End scoping.
    
        _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing Vending_Machine_state_check_first.Machine
    }
    //***** End initializing Vending_Machine_state_check_first
    // **** Start deferred initialize for Vending_Machine_state_check_first
    {
    
    
    
        // **** Start deferred initialize for Vending_Machine_state_check_first.Input
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Vending_Machine_state_check_first.Input.
            vending_machine_state_check_first_input_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Vending_Machine_state_check_first.Input
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Vending_Machine_state_check_first.Input.
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &vending_machine_state_check_first_input_self[0]->base.allocations);
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &vending_machine_state_check_first_input_self[0]->base.allocations);
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &vending_machine_state_check_first_input_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    vending_machine_state_check_first_input_self[0]->_lf__reaction_1.output_produced[count++] = &vending_machine_state_check_first_input_self[0]->_lf_cancel.is_present;
                }
                {
                    vending_machine_state_check_first_input_self[0]->_lf__reaction_1.output_produced[count++] = &vending_machine_state_check_first_input_self[0]->_lf_sel.is_present;
                }
                {
                    vending_machine_state_check_first_input_self[0]->_lf__reaction_1.output_produced[count++] = &vending_machine_state_check_first_input_self[0]->_lf_coin.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of Vending_Machine_state_check_first.Input
        
        }
        // **** End of deferred initialize for Vending_Machine_state_check_first.Input
        // **** Start deferred initialize for Vending_Machine_state_check_first.Output
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Vending_Machine_state_check_first.Output.
            vending_machine_state_check_first_output_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Vending_Machine_state_check_first.Output
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Vending_Machine_state_check_first.Output.
            vending_machine_state_check_first_output_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Vending_Machine_state_check_first.Output
        
        }
        // **** End of deferred initialize for Vending_Machine_state_check_first.Output
        // **** Start deferred initialize for Vending_Machine_state_check_first.Machine
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Vending_Machine_state_check_first.Machine.
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    2, sizeof(trigger_t**),
                    &_nding_machine_state_check_first_machine_self[0]->base.allocations);
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    2, sizeof(int),
                    &_nding_machine_state_check_first_machine_self[0]->base.allocations);
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    2, sizeof(bool*),
                    &_nding_machine_state_check_first_machine_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.output_produced[count++] = &_nding_machine_state_check_first_machine_self[0]->_lf_change.is_present;
                }
                {
                    _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.output_produced[count++] = &_nding_machine_state_check_first_machine_self[0]->_lf_beverage.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Vending_Machine_state_check_first.Machine
        
        }
        // **** End of deferred initialize for Vending_Machine_state_check_first.Machine
    }
    // **** End of deferred initialize for Vending_Machine_state_check_first
    // **** Start non-nested deferred initialize for Vending_Machine_state_check_first
    {
    
    
    
        // **** Start non-nested deferred initialize for Vending_Machine_state_check_first.Input
        {
        
            // For reference counting, set num_destinations for port Vending_Machine_state_check_first.Input.cancel.
            // Iterate over range Vending_Machine_state_check_first.Input.cancel(0,1)->[Vending_Machine_state_check_first.Machine.cancel(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                vending_machine_state_check_first_input_self[src_runtime]->_lf_cancel._base.num_destinations = 1;
                vending_machine_state_check_first_input_self[src_runtime]->_lf_cancel._base.source_reactor = (self_base_t*)vending_machine_state_check_first_input_self[src_runtime];
            }
            // For reference counting, set num_destinations for port Vending_Machine_state_check_first.Input.sel.
            // Iterate over range Vending_Machine_state_check_first.Input.sel(0,1)->[Vending_Machine_state_check_first.Machine.sel(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                vending_machine_state_check_first_input_self[src_runtime]->_lf_sel._base.num_destinations = 1;
                vending_machine_state_check_first_input_self[src_runtime]->_lf_sel._base.source_reactor = (self_base_t*)vending_machine_state_check_first_input_self[src_runtime];
            }
            // For reference counting, set num_destinations for port Vending_Machine_state_check_first.Input.coin.
            // Iterate over range Vending_Machine_state_check_first.Input.coin(0,1)->[Vending_Machine_state_check_first.Machine.coin(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                vending_machine_state_check_first_input_self[src_runtime]->_lf_coin._base.num_destinations = 1;
                vending_machine_state_check_first_input_self[src_runtime]->_lf_coin._base.source_reactor = (self_base_t*)vending_machine_state_check_first_input_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Vending_Machine_state_check_first.Input.cancel(0,1)->[Vending_Machine_state_check_first.Machine.cancel(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of Vending_Machine_state_check_first.Input triggers 1 downstream reactions
                    // through port Vending_Machine_state_check_first.Input.cancel.
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of Vending_Machine_state_check_first.Input, allocate an
                    // array of trigger pointers for downstream reactions through port Vending_Machine_state_check_first.Input.cancel
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &vending_machine_state_check_first_input_self[src_runtime]->base.allocations); 
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range Vending_Machine_state_check_first.Input.sel(0,1)->[Vending_Machine_state_check_first.Machine.sel(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of Vending_Machine_state_check_first.Input triggers 1 downstream reactions
                    // through port Vending_Machine_state_check_first.Input.sel.
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of Vending_Machine_state_check_first.Input, allocate an
                    // array of trigger pointers for downstream reactions through port Vending_Machine_state_check_first.Input.sel
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &vending_machine_state_check_first_input_self[src_runtime]->base.allocations); 
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range Vending_Machine_state_check_first.Input.coin(0,1)->[Vending_Machine_state_check_first.Machine.coin(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of Vending_Machine_state_check_first.Input triggers 1 downstream reactions
                    // through port Vending_Machine_state_check_first.Input.coin.
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of Vending_Machine_state_check_first.Input, allocate an
                    // array of trigger pointers for downstream reactions through port Vending_Machine_state_check_first.Input.coin
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &vending_machine_state_check_first_input_self[src_runtime]->base.allocations); 
                    vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Vending_Machine_state_check_first.Input.cancel(0,1)->[Vending_Machine_state_check_first.Machine.cancel(0,1)] and Vending_Machine_state_check_first.Machine.cancel(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Vending_Machine_state_check_first.Machine.cancel(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Vending_Machine_state_check_first.Machine.cancel's trigger struct.
                        vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &_nding_machine_state_check_first_machine_self[dst_runtime]->_lf__cancel;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges Vending_Machine_state_check_first.Input.sel(0,1)->[Vending_Machine_state_check_first.Machine.sel(0,1)] and Vending_Machine_state_check_first.Machine.sel(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Vending_Machine_state_check_first.Machine.sel(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Vending_Machine_state_check_first.Machine.sel's trigger struct.
                        vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &_nding_machine_state_check_first_machine_self[dst_runtime]->_lf__sel;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 2;
                // Iterate over ranges Vending_Machine_state_check_first.Input.coin(0,1)->[Vending_Machine_state_check_first.Machine.coin(0,1)] and Vending_Machine_state_check_first.Machine.coin(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Vending_Machine_state_check_first.Machine.coin(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Vending_Machine_state_check_first.Machine.coin's trigger struct.
                        vending_machine_state_check_first_input_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &_nding_machine_state_check_first_machine_self[dst_runtime]->_lf__coin;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Vending_Machine_state_check_first.Input
        // **** Start non-nested deferred initialize for Vending_Machine_state_check_first.Output
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for Vending_Machine_state_check_first.Output
        // **** Start non-nested deferred initialize for Vending_Machine_state_check_first.Machine
        {
        
            // For reference counting, set num_destinations for port Vending_Machine_state_check_first.Machine.change.
            // Iterate over range Vending_Machine_state_check_first.Machine.change(0,1)->[Vending_Machine_state_check_first.Output.change(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                _nding_machine_state_check_first_machine_self[src_runtime]->_lf_change._base.num_destinations = 1;
                _nding_machine_state_check_first_machine_self[src_runtime]->_lf_change._base.source_reactor = (self_base_t*)_nding_machine_state_check_first_machine_self[src_runtime];
            }
            // For reference counting, set num_destinations for port Vending_Machine_state_check_first.Machine.beverage.
            // Iterate over range Vending_Machine_state_check_first.Machine.beverage(0,1)->[Vending_Machine_state_check_first.Output.beverage(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                _nding_machine_state_check_first_machine_self[src_runtime]->_lf_beverage._base.num_destinations = 1;
                _nding_machine_state_check_first_machine_self[src_runtime]->_lf_beverage._base.source_reactor = (self_base_t*)_nding_machine_state_check_first_machine_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Vending_Machine_state_check_first.Machine.change(0,1)->[Vending_Machine_state_check_first.Output.change(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of Vending_Machine_state_check_first.Machine triggers 1 downstream reactions
                    // through port Vending_Machine_state_check_first.Machine.change.
                    _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of Vending_Machine_state_check_first.Machine, allocate an
                    // array of trigger pointers for downstream reactions through port Vending_Machine_state_check_first.Machine.change
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &_nding_machine_state_check_first_machine_self[src_runtime]->base.allocations); 
                    _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range Vending_Machine_state_check_first.Machine.beverage(0,1)->[Vending_Machine_state_check_first.Output.beverage(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of Vending_Machine_state_check_first.Machine triggers 1 downstream reactions
                    // through port Vending_Machine_state_check_first.Machine.beverage.
                    _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of Vending_Machine_state_check_first.Machine, allocate an
                    // array of trigger pointers for downstream reactions through port Vending_Machine_state_check_first.Machine.beverage
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &_nding_machine_state_check_first_machine_self[src_runtime]->base.allocations); 
                    _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Vending_Machine_state_check_first.Machine.change(0,1)->[Vending_Machine_state_check_first.Output.change(0,1)] and Vending_Machine_state_check_first.Output.change(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Vending_Machine_state_check_first.Output.change(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Vending_Machine_state_check_first.Output.change's trigger struct.
                        _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &vending_machine_state_check_first_output_self[dst_runtime]->_lf__change;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges Vending_Machine_state_check_first.Machine.beverage(0,1)->[Vending_Machine_state_check_first.Output.beverage(0,1)] and Vending_Machine_state_check_first.Output.beverage(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Vending_Machine_state_check_first.Output.beverage(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Vending_Machine_state_check_first.Output.beverage's trigger struct.
                        _nding_machine_state_check_first_machine_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &vending_machine_state_check_first_output_self[dst_runtime]->_lf__beverage;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Vending_Machine_state_check_first.Machine
    }
    // **** End of non-nested deferred initialize for Vending_Machine_state_check_first
    // Connect inputs and outputs for reactor Vending_Machine_state_check_first.
    // Connect inputs and outputs for reactor Vending_Machine_state_check_first.Input.
    // Connect Vending_Machine_state_check_first.Input.cancel(0,1)->[Vending_Machine_state_check_first.Machine.cancel(0,1)] to port Vending_Machine_state_check_first.Machine.cancel(0,1)
    // Iterate over ranges Vending_Machine_state_check_first.Input.cancel(0,1)->[Vending_Machine_state_check_first.Machine.cancel(0,1)] and Vending_Machine_state_check_first.Machine.cancel(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Vending_Machine_state_check_first.Machine.cancel(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            _nding_machine_state_check_first_machine_self[dst_runtime]->_lf_cancel = (_machine_cancel_t*)&vending_machine_state_check_first_input_self[src_runtime]->_lf_cancel;
        }
    }
    // Connect Vending_Machine_state_check_first.Input.sel(0,1)->[Vending_Machine_state_check_first.Machine.sel(0,1)] to port Vending_Machine_state_check_first.Machine.sel(0,1)
    // Iterate over ranges Vending_Machine_state_check_first.Input.sel(0,1)->[Vending_Machine_state_check_first.Machine.sel(0,1)] and Vending_Machine_state_check_first.Machine.sel(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Vending_Machine_state_check_first.Machine.sel(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            _nding_machine_state_check_first_machine_self[dst_runtime]->_lf_sel = (_machine_sel_t*)&vending_machine_state_check_first_input_self[src_runtime]->_lf_sel;
        }
    }
    // Connect Vending_Machine_state_check_first.Input.coin(0,1)->[Vending_Machine_state_check_first.Machine.coin(0,1)] to port Vending_Machine_state_check_first.Machine.coin(0,1)
    // Iterate over ranges Vending_Machine_state_check_first.Input.coin(0,1)->[Vending_Machine_state_check_first.Machine.coin(0,1)] and Vending_Machine_state_check_first.Machine.coin(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Vending_Machine_state_check_first.Machine.coin(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            _nding_machine_state_check_first_machine_self[dst_runtime]->_lf_coin = (_machine_coin_t*)&vending_machine_state_check_first_input_self[src_runtime]->_lf_coin;
        }
    }
    // Connect inputs and outputs for reactor Vending_Machine_state_check_first.Output.
    // Connect inputs and outputs for reactor Vending_Machine_state_check_first.Machine.
    // Connect Vending_Machine_state_check_first.Machine.change(0,1)->[Vending_Machine_state_check_first.Output.change(0,1)] to port Vending_Machine_state_check_first.Output.change(0,1)
    // Iterate over ranges Vending_Machine_state_check_first.Machine.change(0,1)->[Vending_Machine_state_check_first.Output.change(0,1)] and Vending_Machine_state_check_first.Output.change(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Vending_Machine_state_check_first.Output.change(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            vending_machine_state_check_first_output_self[dst_runtime]->_lf_change = (_output_change_t*)&_nding_machine_state_check_first_machine_self[src_runtime]->_lf_change;
        }
    }
    // Connect Vending_Machine_state_check_first.Machine.beverage(0,1)->[Vending_Machine_state_check_first.Output.beverage(0,1)] to port Vending_Machine_state_check_first.Output.beverage(0,1)
    // Iterate over ranges Vending_Machine_state_check_first.Machine.beverage(0,1)->[Vending_Machine_state_check_first.Output.beverage(0,1)] and Vending_Machine_state_check_first.Output.beverage(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Vending_Machine_state_check_first.Output.beverage(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            vending_machine_state_check_first_output_self[dst_runtime]->_lf_beverage = (_output_beverage_t*)&_nding_machine_state_check_first_machine_self[src_runtime]->_lf_beverage;
        }
    }
    {
        {
            // Add action Vending_Machine_state_check_first.Input.a to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[0] 
                    = &vending_machine_state_check_first_input_self[0]->_lf_a.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action Vending_Machine_state_check_first.Input.a to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[0] 
                    = &vending_machine_state_check_first_input_self[0]->_lf_a.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Vending_Machine_state_check_first.Input.cancel to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_cancel.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Vending_Machine_state_check_first.Input.cancel to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_cancel.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port Vending_Machine_state_check_first.Input.sel to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_sel.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Vending_Machine_state_check_first.Input.sel to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_sel.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port Vending_Machine_state_check_first.Input.coin to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_coin.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Vending_Machine_state_check_first.Input.coin to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[1 + count] = &vending_machine_state_check_first_input_self[0]->_lf_coin.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Vending_Machine_state_check_first.Machine.change to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[4 + count] = &_nding_machine_state_check_first_machine_self[0]->_lf_change.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Vending_Machine_state_check_first.Machine.change to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[4 + count] = &_nding_machine_state_check_first_machine_self[0]->_lf_change.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port Vending_Machine_state_check_first.Machine.beverage to array of is_present fields.
            envs[vending_machine_state_check_first_main].is_present_fields[4 + count] = &_nding_machine_state_check_first_machine_self[0]->_lf_beverage.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Vending_Machine_state_check_first.Machine.beverage to array of intended_tag fields.
            envs[vending_machine_state_check_first_main]._lf_intended_tag_fields[4 + count] = &_nding_machine_state_check_first_machine_self[0]->_lf_beverage.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance Vending_Machine_state_check_first
    {
    
        // Set reaction priorities for ReactorInstance Vending_Machine_state_check_first.Input
        {
            vending_machine_state_check_first_input_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            vending_machine_state_check_first_input_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            vending_machine_state_check_first_input_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance Vending_Machine_state_check_first.Output
        {
            vending_machine_state_check_first_output_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            vending_machine_state_check_first_output_self[0]->_lf__reaction_0.index = 0xffffffffffff0003LL;
            vending_machine_state_check_first_output_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            vending_machine_state_check_first_output_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance Vending_Machine_state_check_first.Machine
        {
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            _nding_machine_state_check_first_machine_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[5] = 
        {1, 1, 1, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 5};
    lf_sched_init(
        &envs[vending_machine_state_check_first_main],
        envs[vending_machine_state_check_first_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        lf_latest_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
