// Code generated by the Lingua Franca compiler from:
// file://Users/sailor/Developer/git/EDAN15/Lab1/lab1_3.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/sailor/Developer/git/EDAN15/src-gen/Lab1/lab1_3"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_source.h"
#include "_sink.h"
#include "_lab1_3_main.h"
typedef enum {
    lab1_3_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[lab1_3_main],"lab1_3",lab1_3_main,_lf_number_of_workers,1,0,0,0,2,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _lab1_3_main_main_self_t* lab1_3_main_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_3_main_self);
    _source_self_t* lab1_3_source_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_3_source_self);
    _sink_self_t* lab1_3_sink_self[1];
    SUPPRESS_UNUSED_WARNING(lab1_3_sink_self);
    // ***** Start initializing lab1_3 of class lab1_3
    lab1_3_main_self[0] = new__lab1_3_main();
    lab1_3_main_self[0]->base.environment = &envs[lab1_3_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
    {
        _lab1_3_main_main_self_t *self = lab1_3_main_self[0];
        // ***** Start initializing lab1_3.Source of class Source
        lab1_3_source_self[0] = new__source();
        lab1_3_source_self[0]->base.environment = &envs[lab1_3_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab1_3_source_self[0]->_lf_out_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initiaizing timer lab1_3.Source.t.
        lab1_3_source_self[0]->_lf__t.offset = SEC(1);
        lab1_3_source_self[0]->_lf__t.period = SEC(1);
        // Associate timer with the environment of its parent
        envs[lab1_3_main].timer_triggers[timer_triggers_count[lab1_3_main]++] = &lab1_3_source_self[0]->_lf__t;
        lab1_3_source_self[0]->_lf__t.mode = NULL;
        // Initializing action lab1_3.Source.a
        lab1_3_source_self[0]->_lf__a.offset = 0;
        lab1_3_source_self[0]->_lf__a.period = -1;
        lab1_3_source_self[0]->_lf__a.last_tag = NEVER_TAG;
        lab1_3_source_self[0]->_lf__a.mode = NULL;
        lab1_3_source_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing lab1_3.Source
    }
    {
        _lab1_3_main_main_self_t *self = lab1_3_main_self[0];
        // ***** Start initializing lab1_3.Sink of class Sink
        lab1_3_sink_self[0] = new__sink();
        lab1_3_sink_self[0]->base.environment = &envs[lab1_3_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        lab1_3_sink_self[0]->_lf_in_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        lab1_3_sink_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing lab1_3.Sink
    }
    //***** End initializing lab1_3
    // **** Start deferred initialize for lab1_3
    {
    
    
    
        // **** Start deferred initialize for lab1_3.Source
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_3.Source.
            lab1_3_source_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab1_3_source_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab1_3_source_self[0]->base.allocations);
            lab1_3_source_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab1_3_source_self[0]->base.allocations);
            lab1_3_source_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab1_3_source_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    lab1_3_source_self[0]->_lf__reaction_0.output_produced[count++] = &lab1_3_source_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of lab1_3.Source
        
        }
        // **** End of deferred initialize for lab1_3.Source
        // **** Start deferred initialize for lab1_3.Sink
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of lab1_3.Sink.
            lab1_3_sink_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of lab1_3.Sink
        
        }
        // **** End of deferred initialize for lab1_3.Sink
    }
    // **** End of deferred initialize for lab1_3
    // **** Start non-nested deferred initialize for lab1_3
    {
    
    
    
        // **** Start non-nested deferred initialize for lab1_3.Source
        {
        
            // For reference counting, set num_destinations for port lab1_3.Source.out.
            // Iterate over range lab1_3.Source.out(0,1)->[lab1_3.Sink.in(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                lab1_3_source_self[src_runtime]->_lf_out._base.num_destinations = 1;
                lab1_3_source_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)lab1_3_source_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range lab1_3.Source.out(0,1)->[lab1_3.Sink.in(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of lab1_3.Source triggers 1 downstream reactions
                    // through port lab1_3.Source.out.
                    lab1_3_source_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of lab1_3.Source, allocate an
                    // array of trigger pointers for downstream reactions through port lab1_3.Source.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &lab1_3_source_self[src_runtime]->base.allocations); 
                    lab1_3_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges lab1_3.Source.out(0,1)->[lab1_3.Sink.in(0,1)] and lab1_3.Sink.in(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range lab1_3.Sink.in(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port lab1_3.Sink.in's trigger struct.
                        lab1_3_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &lab1_3_sink_self[dst_runtime]->_lf__in;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for lab1_3.Source
        // **** Start non-nested deferred initialize for lab1_3.Sink
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for lab1_3.Sink
    }
    // **** End of non-nested deferred initialize for lab1_3
    // Connect inputs and outputs for reactor lab1_3.
    // Connect inputs and outputs for reactor lab1_3.Source.
    // Connect lab1_3.Source.out(0,1)->[lab1_3.Sink.in(0,1)] to port lab1_3.Sink.in(0,1)
    // Iterate over ranges lab1_3.Source.out(0,1)->[lab1_3.Sink.in(0,1)] and lab1_3.Sink.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range lab1_3.Sink.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            lab1_3_sink_self[dst_runtime]->_lf_in = (_sink_in_t*)&lab1_3_source_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor lab1_3.Sink.
    {
        {
            // Add action lab1_3.Source.a to array of is_present fields.
            envs[lab1_3_main].is_present_fields[0] 
                    = &lab1_3_source_self[0]->_lf_a.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action lab1_3.Source.a to array of intended_tag fields.
            envs[lab1_3_main]._lf_intended_tag_fields[0] 
                    = &lab1_3_source_self[0]->_lf_a.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port lab1_3.Source.out to array of is_present fields.
            envs[lab1_3_main].is_present_fields[1 + count] = &lab1_3_source_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port lab1_3.Source.out to array of intended_tag fields.
            envs[lab1_3_main]._lf_intended_tag_fields[1 + count] = &lab1_3_source_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance lab1_3
    {
    
        // Set reaction priorities for ReactorInstance lab1_3.Source
        {
            lab1_3_source_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_3_source_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        }
    
    
        // Set reaction priorities for ReactorInstance lab1_3.Sink
        {
            lab1_3_sink_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            lab1_3_sink_self[0]->_lf__reaction_0.index = 0xffffffffffff0001LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[2] = 
        {1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 2};
    lf_sched_init(
        &envs[lab1_3_main],
        envs[lab1_3_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        lf_latest_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
